# url ou dominio
@URL = http://localhost
# Porta do servidor
@PORT = 3600
# endpoint ou rota do teste
@ENDPOINT = logradouros
# uri - rota final do teste
@URI = {{URL}}:{{PORT}}/{{ENDPOINT}}

GET {{URI}}
###
GET {{URI}}/2

###
POST {{URI}}
Content-Type: application/json; charset=utf-8

     {
      "logradouro": "Jose Bonifacio",
      "tipo" : "rua"
    }

###
PUT {{URI}}/2
Content-Type: application/json; charset=utf-8

  {
      "logradouro": "Carlos Chagas Filho"
  }


###
DELETE {{URI}}/1