# url ou dominio
@URL = http://localhost
# Porta do servidor
@PORT = 3300
# endpoint ou rota do teste
@ENDPOINT = municipios
# uri - rota final do teste
@URI = {{URL}}:{{PORT}}/{{ENDPOINT}}

GET {{URI}}
###
GET {{URI}}/11

###
POST {{URI}}
Content-Type: application/json; charset=utf-8

  {
      "municipio": "Ribeirao Preto",
      "estado" : "SP",
      "populacao" : 650000
  }

###
PUT {{URI}}/11
Content-Type: application/json; charset=utf-8

  {
      "municipio": "Ribeirão Preto",
      "estado" : "SP",
      "populacao" : 650000
  }


###
DELETE {{URI}}/1